"""Initial

Revision ID: e05744bc2502
Revises: 
Create Date: 2026-08-13 19:13:40.078287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05744bc2502'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_classes',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('students',
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('qr_token', sa.String(length=36), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_qr_token'), 'students', ['qr_token'], unique=True)
    op.create_table('attendance_events',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('SCHOOL_ENTER', 'SCHOOL_EXIT', 'LESSON_PRESENT', 'BOARDING_PRESENT', name='attendanceeventtype'), nullable=False),
    sa.Column('source', sa.Enum('CAMERA', 'TEACHER', 'SCANNER', name='attendancesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_created_at'), 'attendance_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_attendance_events_student_id'), 'attendance_events', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_events_student_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_created_at'), table_name='attendance_events')
    op.drop_table('attendance_events')
    op.drop_index(op.f('ix_students_qr_token'), table_name='students')
    op.drop_table('students')
    op.drop_table('school_classes')
    # ### end Alembic commands ###
